# curl -X POST http://localhost:8080/api/qnaboard/create
#-H "Content-Type: multipart/form-data"
#-F 'requestDto={"memberId":1,"title":"게시글 제목","content":"게시글 내용"};type=application/json'
#-F 'files=@C:/path/to/your/file1.png'
#-F 'files=@C:/path/to/your/file2.png'
### 게시글 작성 요청 ver3
POST http://localhost:8080/api/qnaboard/create
Authorization: Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBQ0NFU1MiLCJpYXQiOjE3MzcxNzQxMTUsImV4cCI6MTczNzE3NTAxNSwibWVtYmVySWQiOjEsInJvbGUiOiJVU0VSIn0._IArbVO2atPGnEcGzJyE8njfENrhn4ezc-GpkLpV3guax7e_AH6J7HiXW-qRqOKfbNsMpWPaOrPDtUE8zSH_iQ
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="requestDto"

{"memberId":1,"title":"게시글 제목","content":"게시글 내용"}
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file1.png"

< C:\Users\User\bigproject\test\file1.png
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file1.png"

< C:\Users\User\bigproject\test\file1.png
--WebAppBoundary--





# curl -X POST http://localhost:8080/api/qnaboard/create
#-H "Content-Type: multipart/form-data"
#-F 'requestDto={"memberId":1,"title":"게시글 제목","content":"게시글 내용"};type=application/json'
#-F 'files=@C:/path/to/your/file1.png'
#-F 'files=@C:/path/to/your/file2.png'
### 게시글 작성 요청 v2
POST http://localhost:8080/api/qnaboard/create
Authorization: Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBQ0NFU1MiLCJpYXQiOjE3MzcyMDA1ODEsImV4cCI6MTczNzIwMTQ4MSwibWVtYmVySWQiOjEsInJvbGUiOiJVU0VSIn0.5yOQyCUzFXqilK6jxbxUYDS5UlIZjW4kIUZWaShIuZ_Y7kNU8DLQoyBGi0nwDMaQcjWA2cJFUCkTcdl2ceePUA
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="requestDto"

{"memberId":1,"title":"게시글 제목","content":"게시글 내용"}
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file1.png"

< C:\Users\User\bigproject\test\file1.png
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file1.png"

< C:\Users\User\bigproject\test\file1.png
--WebAppBoundary--

### 첨부파일 하나 업로드 API
# curl -X POST "http://localhost:8080/api/files/update/{fileId}"
# -H "Content-Type: multipart/form-data"
# -F "file=@/path/to/your/file"
POST http://localhost:8080/api/files/update/1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file1.png"

< \path\to\your\file1.png
--WebAppBoundary--

### 첨부파일 대량 업로드 API
# curl -X POST http://localhost:8080/api/files/upload
#-H "Authorization: Bearer {your_jwt_token}"
#-H "Content-Type: multipart/form-data"
#-F "files=@/path/to/your/file1.png"
#-F "files=@/path/to/your/file2.png"
POST http://localhost:8080/api/files/upload
Authorization: Bearer {your_jwt_token}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file1.png"

< \path\to\your\file1.png
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file2.png"

< \path\to\your\file2.png
--WebAppBoundary--

###


###
GET http://localhost:8080/api/qnaboard/test
Content-Type: application/json
###

